### ISSUE TITLE
Minimize to tray causing duplicate tray icons

### ISSUE THREAD

**Issue by johnjacobkenny** [Splode/pomotroid#127]
I was toggling the option _Minimize to Tray_ on and off and now I have a few icons in the tray. Only one of the icons interacts with the app. When I close the app, all tray icons go away.

Technically, I think that when _Minimize to Tray_ is unchecked, the tray icon is not going away. I'm on Linux and using Gnome.

![image](https://user-images.githubusercontent.com/19240564/94106305-caba3700-fe58-11ea-8989-c6e165808348.png)

**Comment by Splode** [comment]
@johnjacobkenny Is this happening all the time, or only in development? It happens in development due to hot-reloading. When the application reloads, it creates a new tray icon. The previous icon doesn't get cleared until the overall process is killed.

If it's happening during normal operation, then it's unexpected behavior.
