### ISSUE TITLE
Setting, "Always On Top" is not preserved on application startup.

### ISSUE THREAD

**Issue by jumpnett** [Splode/pomotroid#30]
**Expected Behavior:**
When I enable the setting "Always On Top", close the app, and reopen it, the app should still exhibit the "Always On Top" behavior.

**Actual Behavior:**
When I enable the setting "Always On Top", close the app, and reopen it, the app does not exhibit the "Always On Top" behavior, even though the setting is still enabled.

**Work around:**
Disabling "Always On Top", and then re-enabling restores the proper behavior.

**Version**
installed: X-AppImage-BuildId=1bdaf0f0-b155-11a8-347f-85bfaa8fbf9c image: X-AppImage-BuildId=1bdaf0f0-b155-11a8-347f-85bfaa8fbf9c

**Comment by Splode** [comment]
I'm unable to replicate this, but it may be related to #27, which was fixed. What OS are you using?

**Comment by jumpnett** [comment]
Ubuntu 18.4

**Comment by Splode** [comment]
This seems to be an issue with electron on Ubuntu 18.04 (see [https://github.com/electron/electron/issues/12445](https://github.com/electron/electron/issues/12445))

Luckily, there is a workaround and has been fixed with 9f72b034e6bb93c295227fbf15fcf7409e57fa6f and will be available in the v0.4.1 release.

**Comment by jumpnett** [comment]
Sweet, it works.  Thanks.
